name: "barlow_twins_test"
ckpt_path: "/home/doronser/storage/brats18_projects/fine_tune_ckpts/"

data:
  dir: "/raid/data/users/doronser/MICCAI_BraTS_2018_Data_Training/"
  batch_size: 4
  num_workers: 16
  val_split_size: 0.1
  ssl: False
  preprocessing:
#      ZNormalization:
#        masking_method:
  augmentations:
    RandomAffine:
      scales:
        - 0.9
        - 1.1
      degrees: 0
      translation: 0
    RandomFlip:
      axes:
        - 0
        - 1
        - 2
#    RandomNoise:
#      mean: 0
#      std: 0.025
# TODO: add random crop?

model:
  wandb_path: 'bio-vision-lab/intro2dl_brats2018/bm7ppl2d'

trainer:
  epochs: 100
  gpu: 2

optimizer:
  name: 'Adam'
  lr: 1.e-4
  weight_decay: 5.e-5
  eps: 1.e-8

scheduler:
#  name: 'CosineAnnealingLR'
#  T_max: 5.
#  eta_min: 1.e-6
  name: 'ExponentialLR'
  gamma: 0.95




